### ISSUE TITLE
LSTM pretrained model link is broken

### ISSUE THREAD

**Issue by songheony** [yyc9268/Deep-TAMA#1]
The link (https://drive.google.com/open?id=1lETIh-5seYzdXEpy4WZj8Z9JPx4Fvuc3) is broken.

**Comment by yyc9268** [comment]
Sorry for your inconvenience. The link has been recovered.
**Please download both of JI-Net and LSTM model again!**

**Comment by songheony** [comment]
Thanks for the quick fix!
